package com.example.springboot.part0304mybatisgenerator.mapper;

import com.example.springboot.part0304mybatisgenerator.entity.Dog;
import java.util.List;

public interface DogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbg.generated
     */
    int insert(Dog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbg.generated
     */
    Dog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbg.generated
     */
    List<Dog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dog
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dog record);
}