server:
  port: 8080
spring:
  application:
    name: testing
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./spring-boot-example/B.features/testing/h2database_data/test_db;MODE=MYSQL
    username: admin
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update