server:
  port: 9001
spring:
  application:
    name: spring-boot-admin-client
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:9999
management:
  endpoints:
    web:
      exposure:
        include: "*"
