server:
  port: 8090
spring:
  application:
    name: kaptcha
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./temp/h2database_data/test_db;MODE=MYSQL
    username: admin
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
kaptcha:
  enable: true
  text-producer:
    char-length: 4
    char-string: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  image:
    width: 110
    height: 36