spring:
  application:
    name: hello world
server:
  port: 8090
  tomcat:
    basedir: ./temp/tomcat
    accesslog:
      enabled: true
      directory: accesslog
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i'
