server:
  port: 8080
spring:
  application:
    name: transaction-multi-datasource-demo
  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/db1
      username: root
      password: 123456
    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/db2
      username: root
      password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jta:
    enabled: true
    # @see com.atomikos:transactions / transactions-defaults.properties
    # @see com.atomikos.icatch.provider.imp.AssemblerImp
    atomikos:
      properties:
        enable-logging: true
        log-base-dir: ./temp/logs/atomikos-logs/
        log-base-name: tmlog
      datasource:
        min-pool-size: 5
        max-pool-size: 20
