server:
  port: 8080
spring:
  application:
    name: spring-data-jdbc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./spring-boot-example/B.features/jdbc/spring-data-jdbc/temp/h2database_data/test_db;MODE=MYSQL
    username: admin
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql