spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: -1 # Random port
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.example.dubbo.provider.service