spring:
  application:
    name: sending-email
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: xxx@qq.com
    password: xxx
    default-encoding: utf-8
    properties.mail.debug: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.starttls.required: false
    properties.mail.smtp.connectiontimeout: 5000
    properties.mail.smtp.timeout: 3000
    properties.mail.smtp.writetimeout: 5000
    # proxy
    # properties:
      # proxySet: true
      # mail.smtp.socks.host: xxx
      # mail.smtp.socks.port: xxx

# https://javaee.github.io/javamail/