spring:
  application:
    name: logging
server:
  port: 8080
  tomcat:
    basedir: spring-boot-example/B.features/logging/temp/tomcat
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      directory: logs
logging:
  config: classpath:logback-spring.xml
  file:
    path: spring-boot-example/B.features/logging/temp/service/logs