server:
  port: 8090
spring:
  application:
    name: jsch
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

file:
  upload-base-path: ./temp/upload

remote:
  host:
  port: 22
  user:
  password: