server:
  port: 8080
spring:
  application:
    name: flyway-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./temp/h2database_data/test_db;MODE=MYSQL
    username: admin
    password: 123456
  jpa:
    show-sql: true
  flyway:
    # 是否开启flyway
    enabled: true
    # baseline-on-migrate：当schema为空时，是否自动执行基线。配置为true时，第一次启动flyway时，会自动创建flyway记录版本的表flyway_schema_history，以及基线记录（V1基线记录）
    baseline-on-migrate: true
    # 扫描的sql脚本位置
    locations: classpath:db/migration
    # V(Versioned Migrations)，用于版本升级，每个版本都有唯一的版本号并只能执行一次。
    sql-migration-prefix: V
    # R(Repeatable Migrations)，可重复加载的 migration，一旦脚本的 checkksum 有变动，flyway 就会重新应用该脚本，它并不用于版本更新，这类的 migration 总是在 versioned migration 执行之后才被执行，可以用于存放view/procedures/functions/packages...
    repeatable-sql-migration-prefix: R
    # 自动生成的记录版本表名
    table: flyway_schema_history
    # sql命名中间分隔符
    sql-migration-separator: __
    # sql文件后缀名
    sql-migration-suffixes: .sql
