server:
  port: 8080
spring:
  application:
    name: mybatis-plus-integration-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./temp/h2database_data/test_db;MODE=MYSQL
    username: admin
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
mybatis-plus:
  mapper-locations:
    - classpath:**/*Mapper.xml
  type-aliases-package: com.example.mybatis.plus.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
